### PR TITLE
Report text resource save errors to user

### LINKED ISSUE #153: Text resource status bar falsely reports "Saved" despite expired session
If a user begins editing a text resource and their session expires (either through logout or application relaunch), further changes to the text will fail to save to the database; the status bar at the base of the text resource viewer, however, will continue to report "Saved" after the window attempts to save the updated text.

### PR DESCRIPTION
**Pull request by akstuhl**
### What does this PR do?
Adds error reporting for text resources when a save request is unsuccessful. In the event of a save failure, an alert will appear encouraging the user to refresh their browser window, and the text resource's status bar will read "Save failed" instead of "Saved."

### What issues does it address?
Closes #153 

### How to test
- On [staging](http://dm-staging.middell.net), open a project with a text resource and make some changes to its text. Confirm that the status bar at the bottom of the text resource viewer reads "Saving..." after a change is made and then "Saved" after a moment.
- Break the connection between the front-end and the server by turning off your internet connection. Then add more text to the same resource. An alert should fire telling you there's been a save error.
- Close the alert and check that the text resource's status bar now reads "Save failed"
- Instead of refreshing your browser window, turn your internet connection back on. Make another change to the resource's text. The status bar should return to its "Saving..." / "Saved" display.

### CODE REVIEW

File: src/main/resources/static/js/dm/viewer/TextEditor.js [hunk 1]
```diff
@@ -172,7 +172,11 @@ dm.viewer.TextEditor.prototype.saveContents = function() {
     var highlightPlugin = this.field.getPluginByClassId('Annotation');
     highlightPlugin.updateAllHighlightResources();
 
-    this.databroker.sync();
+    var request = this.databroker.sync();
+    request.fail(function(response) {
+      this.saveError = true;
+      alert("Error: failed to save changes to text resource. Please refresh your browser window to avoid losing progress.");
```
Comment (jamiefolsom) [inline src/main/resources/static/js/dm/viewer/TextEditor.js]: Would this lead to people reloading the page with unsaved data, and therefore lose that data?

**Review by jamiefolsom — COMMENTED** [review]
Presumably, a user isn't going to compose an essay with no internet connection. Maybe the error message says "copy/paste your annotation content into a local file, then refresh". Open to suggestions on the UX here. Or: "reconnect to the internet before closing this window, and make another change, to trigger save".

File: src/main/resources/static/js/dm/viewer/TextEditor.js (hunk 1 above)
Comment (akstuhl) [reply src/main/resources/static/js/dm/viewer/TextEditor.js]: Good points @jamiefolsom  — I was envisioning a use case where a problem with the user's session necessitates reconnecting to the backend (vs. the test case of breaking that link via device internet connection), but the UX should also account for device connection problems. If it's a session problem, a refresh would be needed since the user would need to log back in. What do you think of "Error: failed to save changes to text resource. Please copy any in-progress text to a local file, then check your internet connection and refresh your browser window."?

Comment (jamiefolsom) [reply src/main/resources/static/js/dm/viewer/TextEditor.js]: @akstuhl perfect. Otherwise great, from my pt. of view! 👍

**Comment by SteveMarvin** [comment]
Test plan successful. 👍
